pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                bat 'node -v'
                bat 'npm -v'
                bat 'npm install'
                bat 'npm build'
            }
        }
    }
}